title: Tsegaye M. Tashu
description: AI & NLP Researcher | Educator | Multilingual Tech Enthusiast
theme: minima
author: Tsegaye M. Tashu
email: your.t.m.tashu@rug.nl
github_username: your-username

nav:
  - Home: /
  - About: /about
  - Courses: /courses
